"""Initial revision

Revision ID: 234eba4d359d
Revises: 
Create Date: 2022-11-27 21:51:46.832077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234eba4d359d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
