name: Base actions
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - ".github/workflows/*"
  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Pull Repo
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
      - name: Lint
        run: flake8
      - name: Run tests
        run: pytest